# Generated by Django 3.2.4 on 2021-06-14 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='telegram_username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
