# Generated by Django 3.2.4 on 2021-06-14 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytattoo',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=120, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorytattoo',
            name='name',
            field=models.CharField(help_text='Например: Спина, Руки, Ноги, Грудь', max_length=100, verbose_name='Название'),
        ),
    ]
