# Generated by Django 3.2.4 on 2021-06-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Татуировку', 'verbose_name_plural': 'Татуировки'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_category', to='gallery.categorytattoo', verbose_name='Категория'),
        ),
    ]
