# Generated by Django 3.2.4 on 2021-06-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationblock',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество посещений'),
        ),
    ]
