# Generated by Django 3.2.4 on 2021-06-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_informationblock_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Home', 'Главная страница'), ('About', "Страница 'О нас'")], max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-name'],
            },
        ),
    ]
