# Generated by Django 3.2.4 on 2021-06-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='about/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
