# Generated by Django 3.2.4 on 2021-06-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Главная страница', "Страница 'О нас'")], max_length=100, verbose_name='Название категории'),
        ),
    ]
