# Generated by Django 3.2.4 on 2021-06-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Home', 'Главная страница'), ('About', "Страница 'О нас'")], max_length=100, verbose_name='Название категории'),
        ),
    ]
