# Generated by Django 3.2.4 on 2021-07-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
