# Generated by Django 3.2.4 on 2021-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('telegram_id', models.CharField(max_length=15, verbose_name='Телеграм ID')),
                ('message', models.TextField(max_length=500, verbose_name='Текст сообщения')),
            ],
        ),
    ]
