# Generated by Django 3.2.4 on 2021-06-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_workstattoomasters_options'),
        ('contact', '0002_alter_contactmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTelegramId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=15, verbose_name='Телеграм ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Телеграм ID',
                'verbose_name_plural': 'Телеграм ID',
            },
        ),
    ]
