# Generated by Django 3.2.4 on 2021-06-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_workstattoomasters_options'),
        ('contact', '0003_admintelegramid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintelegramid',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_id', to='master.master', verbose_name='Мастер'),
        ),
    ]
