# Generated by Django 3.2.4 on 2021-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_admintelegramid_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='telegram_username',
            field=models.CharField(default='', max_length=100, verbose_name='Username'),
        ),
    ]
