# Generated by Django 3.2.4 on 2021-06-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactmodel_telegram_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='telegram_id',
        ),
    ]
