# Generated by Django 3.2.4 on 2021-06-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя мастера')),
                ('image', models.ImageField(upload_to='masters/', verbose_name='Изображение мастера')),
                ('about_master', models.TextField(verbose_name='Информация о мастере')),
                ('vk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ВК')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Instagram')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Telegram')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorksTattooMasters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works_masters/', verbose_name='Изображения')),
            ],
        ),
    ]
