# Generated by Django 3.2.4 on 2021-06-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_workstattoomasters_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: название категории татуировки - Блекворк, Олд-скул', max_length=50, verbose_name='Название')),
                ('value', models.IntegerField(help_text='От 1 до 100', verbose_name='Значение')),
            ],
        ),
        migrations.DeleteModel(
            name='WorksTattooMasters',
        ),
    ]
