# Generated by Django 3.2.4 on 2021-06-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210618_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterskills',
            options={'ordering': ['name'], 'verbose_name': 'Умение мастера', 'verbose_name_plural': 'Умения мастера'},
        ),
        migrations.AlterField(
            model_name='masterskills',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='masterskills',
            name='value',
            field=models.PositiveSmallIntegerField(verbose_name='Значение (%)'),
        ),
    ]
