# Generated by Django 3.2.4 on 2021-06-18 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20210618_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterskills',
            name='value',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MaxValueValidator(1)], verbose_name='Значение (%)'),
        ),
    ]
