# Generated by Django 3.2.4 on 2021-06-20 10:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_masterskills_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterskills',
            name='master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='master.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='masterskills',
            name='value',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Значение (%)'),
        ),
    ]
