# Generated by Django 3.2.4 on 2021-06-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20210620_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterskills',
            name='master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='master_skills', to='master.master', verbose_name='Мастер'),
        ),
    ]
