# Generated by Django 3.2.4 on 2021-06-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_masterskills_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordToMasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('telegram_username', models.CharField(default='', max_length=100, verbose_name='Username')),
                ('message', models.TextField(max_length=500, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-name'],
            },
        ),
    ]
