# Generated by Django 3.2.4 on 2021-06-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_recordtomastermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtomastermodel',
            name='master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='master_to_record', to='master.master', verbose_name='Мастер'),
        ),
    ]
