# Generated by Django 3.2.4 on 2021-06-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_recordtomastermodel_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='about_master',
            field=models.TextField(max_length=180, verbose_name='Информация о мастере'),
        ),
    ]
